import { Inter } from "next/font/google"
import { UserProvider } from '@auth0/nextjs-auth0/client'

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const DefaultLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  )
}

export default DefaultLayout
