import Link from 'next/link'
import { getSession } from '@auth0/nextjs-auth0'

import LoginLogout from '../components/LoginLogout'
import HeaderMenu from '../components/HeaderMenu'
import ConnectSupabase from '../components/ConnectSupabase'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
}

const DefaultLayout = async ({ children }) => {
  const session = await getSession()
  const isAuthenticated = Boolean(session?.user)

  return (
    <>
      <div className="bg-[#121212]">
        <div className="mx-auto max-w-screen-2xl px-4 md:px-8">
          <header className="mb-4 flex flex-col items-center justify-between gap-8 py-2 md:flex-row md:gap-0 md:py-2">
            {/* <!-- logo - start --> */}
            <Link
              href="/"
              className="inline-flex items-center gap-2.5 p-1"
              aria-label="logo"
            >
              {/* <LogoIconComponent /> */}
            </Link>
            {/* <!-- logo - end --> */}

            <HeaderMenu isAuthenticated={isAuthenticated} />

            {/* <!-- buttons - start --> */}
            <LoginLogout className="hidden w-60 justify-end py-3 transition duration-100 lg:flex" />
          </header>
        </div>
      </div>

      <ConnectSupabase />

      {children}

      {/* <!-- footer - start --> */}
      <footer className="bg-[#121212]">
        <div className="pt-12 lg:pt-16">
          <div className="mx-auto max-w-screen-2xl px-4 md:px-8">
            <div className="mb-8">
              <div className="flex flex-col items-center justify-between md:flex-row">
                <p className="mb-6 text-center text-gray-500">
                  Nice charts and data representation for your social media.
                </p>

                {/* <!-- social - start --> */}
                <div className="flex items-center gap-4 text-gray-500">
                  Contact us via
                  <a
                    target="_blank"
                    rel="noreferrer"
                    href="https://discord.gg/WaSSJNjmUZ"
                    className="text-gray-400 transition duration-100 hover:text-gray-500 active:text-gray-600"
                  >
                    <svg
                      className="h-5 w-5"
                      width="24"
                      height="24"
                      viewBox="0 0 127.14 96.36"
                      fill="currentColor"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M107.7,8.07A105.15,105.15,0,0,0,81.47,0a72.06,72.06,0,0,0-3.36,6.83A97.68,97.68,0,0,0,49,6.83,72.37,72.37,0,0,0,45.64,0,105.89,105.89,0,0,0,19.39,8.09C2.79,32.65-1.71,56.6.54,80.21h0A105.73,105.73,0,0,0,32.71,96.36,77.7,77.7,0,0,0,39.6,85.25a68.42,68.42,0,0,1-10.85-5.18c.91-.66,1.8-1.34,2.66-2a75.57,75.57,0,0,0,64.32,0c.87.71,1.76,1.39,2.66,2a68.68,68.68,0,0,1-10.87,5.19,77,77,0,0,0,6.89,11.1A105.25,105.25,0,0,0,126.6,80.22h0C129.24,52.84,122.09,29.11,107.7,8.07ZM42.45,65.69C36.18,65.69,31,60,31,53s5-12.74,11.43-12.74S54,46,53.89,53,48.84,65.69,42.45,65.69Zm42.24,0C78.41,65.69,73.25,60,73.25,53s5-12.74,11.44-12.74S96.23,46,96.12,53,91.08,65.69,84.69,65.69Z" />
                    </svg>
                  </a>
                </div>
                {/* <!-- social - end --> */}
              </div>
            </div>

            <div className="py-8 text-center text-sm text-gray-400">
              &copy; 2023 {process.env.NEXT_PUBLIC_APP_NAME}
            </div>
          </div>
        </div>
      </footer>
      {/* <!-- footer - end --> */}
    </>
  )
}

export default DefaultLayout
